### ISSUE TITLE
If no connections made

### ISSUE THREAD

**Issue by Alexey-T** [mtxr/CudaText-SQLTools#10]
then almost all commands give error

```
 File "/home/user/.cudatext/py/cuda_sqltools/__init__.py", line 61, in getConnections
    options = connections.get('connections', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

need to add "if connections:"

**Comment by Alexey-T** [comment]
if no queries, then "save query" gives

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_sqltools/__init__.py", line 289, in saveQuery
    queries.add(alias, query)
AttributeError: 'NoneType' object has no attribute 'add'
```

**Comment by mtxr** [comment]
Still a prototype, but it's all working here.

Ubuntu 16.10, latest cudatext
