### ISSUE TITLE
ST can't load connections

### ISSUE THREAD

**Issue by glebmezh** [mtxr/CudaText-SQLTools#25]
ST: Select Connection produces the following error:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/Users/gmezhanskiy/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 292, in run
    ST.selectConnection()
  File "/Users/gmezhanskiy/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 200, in selectConnection
    ST.connectionList = getConnections()
  File "/Users/gmezhanskiy/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 59, in getConnections
    options = connections.get('connections', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

ST v0.6.4
Sublime Text 3 Build 3126
MacOS 10.11.6

SQLToolsConnections.sublime-settings exists and is a valid JSON

**Comment by Alexey-T** [comment]
this is repo for the Cudatext plugin...

**Comment by glebmezh** [comment]
OK sorry, closing
